"""add distance_km and step_calorie to health_entries

Revision ID: 1638d9403e33
Revises: a8f3c1d2e4b7
Create Date: 2026-06-04 17:21:01.792279

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1638d9403e33"
down_revision = "a8f3c1d2e4b7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index("ix_asset_type", ["asset_type"], unique=False)

    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index("ix_event_start_time", ["start_time"], unique=False)

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index("ix_contact_category", ["category"], unique=False)
        batch_op.create_index("ix_contact_name", ["name"], unique=False)

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index("ix_doc_folder_id", ["folder_id"], unique=False)

    with op.batch_alter_table("financial_transactions", schema=None) as batch_op:
        batch_op.create_index("ix_tx_category", ["category"], unique=False)
        batch_op.create_index("ix_tx_date", ["date"], unique=False)
        batch_op.create_index("ix_tx_type_date", ["type", "date"], unique=False)

    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.create_index("ix_goal_status", ["status"], unique=False)

    with op.batch_alter_table("health_entries", schema=None) as batch_op:
        batch_op.add_column(sa.Column("distance_km", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("step_calorie", sa.Integer(), nullable=True))
        batch_op.create_index("ix_health_date", ["date"], unique=False)

    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.create_index("ix_journal_date", ["date"], unique=False)

    with op.batch_alter_table("learning_items", schema=None) as batch_op:
        batch_op.create_index("ix_learning_status", ["status"], unique=False)
        batch_op.create_index("ix_learning_type", ["item_type"], unique=False)

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_tasks_category", ["category"], unique=False)
        batch_op.create_index("ix_tasks_due_date", ["due_date"], unique=False)
        batch_op.create_index("ix_tasks_is_habit", ["is_habit"], unique=False)
        batch_op.create_index("ix_tasks_status", ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_status")
        batch_op.drop_index("ix_tasks_is_habit")
        batch_op.drop_index("ix_tasks_due_date")
        batch_op.drop_index("ix_tasks_category")

    with op.batch_alter_table("learning_items", schema=None) as batch_op:
        batch_op.drop_index("ix_learning_type")
        batch_op.drop_index("ix_learning_status")

    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_journal_date")

    with op.batch_alter_table("health_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_health_date")
        batch_op.drop_column("step_calorie")
        batch_op.drop_column("distance_km")

    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index("ix_goal_status")

    with op.batch_alter_table("financial_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_tx_type_date")
        batch_op.drop_index("ix_tx_date")
        batch_op.drop_index("ix_tx_category")

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_doc_folder_id")

    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index("ix_contact_name")
        batch_op.drop_index("ix_contact_category")

    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_index("ix_event_start_time")

    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_type")

    # ### end Alembic commands ###
