"""initial schema

Revision ID: 54422a558e94
Revises:
Create Date: 2026-06-04 08:49:30.411082

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54422a558e94"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("asset_type", sa.String(length=50), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("cost_basis", sa.Float(), nullable=True),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("broker_platform", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.create_index("ix_asset_type", ["asset_type"], unique=False)

    op.create_table(
        "budget_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("budget_limit", sa.Float(), nullable=True),
        sa.Column("color", sa.String(length=7), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "calendar_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("is_all_day", sa.Boolean(), nullable=True),
        sa.Column("reminder", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.create_index("ix_event_start_time", ["start_time"], unique=False)

    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("company", sa.String(length=100), nullable=True),
        sa.Column("job_title", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.create_index("ix_contact_category", ["category"], unique=False)
        batch_op.create_index("ix_contact_name", ["name"], unique=False)

    op.create_table(
        "folders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["folders.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.create_index("ix_goal_status", ["status"], unique=False)

    op.create_table(
        "health_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("steps", sa.Integer(), nullable=True),
        sa.Column("workout_minutes", sa.Integer(), nullable=True),
        sa.Column("mood", sa.String(length=20), nullable=True),
        sa.Column("sleep_hours", sa.Float(), nullable=True),
        sa.Column("water_liters", sa.Float(), nullable=True),
        sa.Column("calories_in", sa.Integer(), nullable=True),
        sa.Column("calories_out", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("health_entries", schema=None) as batch_op:
        batch_op.create_index("ix_health_date", ["date"], unique=False)

    op.create_table(
        "journal_entries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("mood", sa.String(length=20), nullable=True),
        sa.Column("tags", sa.String(length=200), nullable=True),
        sa.Column("is_favorite", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.create_index("ix_journal_date", ["date"], unique=False)

    op.create_table(
        "learning_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("item_type", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("progress", sa.Integer(), nullable=True),
        sa.Column("author", sa.String(length=100), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("learning_items", schema=None) as batch_op:
        batch_op.create_index("ix_learning_status", ["status"], unique=False)
        batch_op.create_index("ix_learning_type", ["item_type"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("is_habit", sa.Boolean(), nullable=True),
        sa.Column("habit_frequency", sa.String(length=20), nullable=True),
        sa.Column("streak", sa.Integer(), nullable=True),
        sa.Column("last_completed_on", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index("ix_tasks_category", ["category"], unique=False)
        batch_op.create_index("ix_tasks_due_date", ["due_date"], unique=False)
        batch_op.create_index("ix_tasks_is_habit", ["is_habit"], unique=False)
        batch_op.create_index("ix_tasks_status", ["status"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=200), nullable=False),
        sa.Column("original_name", sa.String(length=200), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("upload_date", sa.DateTime(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("tags", sa.String(length=200), nullable=True),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.create_index("ix_doc_folder_id", ["folder_id"], unique=False)

    op.create_table(
        "financial_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("asset_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["asset_id"], ["assets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("financial_transactions", schema=None) as batch_op:
        batch_op.create_index("ix_tx_category", ["category"], unique=False)
        batch_op.create_index("ix_tx_date", ["date"], unique=False)
        batch_op.create_index("ix_tx_type_date", ["type", "date"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("financial_transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_tx_type_date")
        batch_op.drop_index("ix_tx_date")
        batch_op.drop_index("ix_tx_category")

    op.drop_table("financial_transactions")
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_index("ix_doc_folder_id")

    op.drop_table("documents")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index("ix_tasks_status")
        batch_op.drop_index("ix_tasks_is_habit")
        batch_op.drop_index("ix_tasks_due_date")
        batch_op.drop_index("ix_tasks_category")

    op.drop_table("tasks")
    with op.batch_alter_table("learning_items", schema=None) as batch_op:
        batch_op.drop_index("ix_learning_type")
        batch_op.drop_index("ix_learning_status")

    op.drop_table("learning_items")
    with op.batch_alter_table("journal_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_journal_date")

    op.drop_table("journal_entries")
    with op.batch_alter_table("health_entries", schema=None) as batch_op:
        batch_op.drop_index("ix_health_date")

    op.drop_table("health_entries")
    with op.batch_alter_table("goals", schema=None) as batch_op:
        batch_op.drop_index("ix_goal_status")

    op.drop_table("goals")
    op.drop_table("folders")
    with op.batch_alter_table("contacts", schema=None) as batch_op:
        batch_op.drop_index("ix_contact_name")
        batch_op.drop_index("ix_contact_category")

    op.drop_table("contacts")
    with op.batch_alter_table("calendar_events", schema=None) as batch_op:
        batch_op.drop_index("ix_event_start_time")

    op.drop_table("calendar_events")
    op.drop_table("budget_categories")
    with op.batch_alter_table("assets", schema=None) as batch_op:
        batch_op.drop_index("ix_asset_type")

    op.drop_table("assets")
    # ### end Alembic commands ###
