"""add heart rate and sleep session tables

Revision ID: e7067fb7267e
Revises: 54422a558e94
Create Date: 2026-06-04 09:27:12.754520

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e7067fb7267e"
down_revision = "54422a558e94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heart_rate_samples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("bpm", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("heart_rate_samples", schema=None) as batch_op:
        batch_op.create_index("ix_hr_source_timestamp", ["source", "timestamp"], unique=False)
        batch_op.create_index("ix_hr_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "sleep_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("stages_json", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sleep_sessions", schema=None) as batch_op:
        batch_op.create_index("ix_sleep_source_start", ["source", "start_time"], unique=False)
        batch_op.create_index("ix_sleep_start", ["start_time"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sleep_sessions", schema=None) as batch_op:
        batch_op.drop_index("ix_sleep_start")
        batch_op.drop_index("ix_sleep_source_start")

    op.drop_table("sleep_sessions")
    with op.batch_alter_table("heart_rate_samples", schema=None) as batch_op:
        batch_op.drop_index("ix_hr_timestamp")
        batch_op.drop_index("ix_hr_source_timestamp")

    op.drop_table("heart_rate_samples")
    # ### end Alembic commands ###
